---
  version: 2.1
  jobs:
    lint:
      docker:
        - image: circleci/node:12
      steps:
        - checkout
        - restore_cache:
            name: Restore yarn package cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "jest-puppeteer-vuetify-test/yarn.lock"}}
              - yarn-packages-{{ checksum "yarn.lock" }}
              - yarn-packages-
        - run:
            name: Install dependencies
            command: yarn install --frozen-lockfile
        - save_cache:
            name: Save yarn package cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn
        - run:
            name: Lint project
            command: yarn run lint
    build:
      docker:
        - image: circleci/node:12
      steps:
        - checkout
        - restore_cache:
            name: Restore yarn package cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "jest-puppeteer-vuetify-test/yarn.lock"}}
              - yarn-packages-{{ checksum "yarn.lock" }}
              - yarn-packages-
        - run:
            name: Install dependencies
            command: yarn install --frozen-lockfile
        - save_cache:
            name: Save yarn package cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn
        - run:
            name: Build project
            command: yarn run build
    test:
      docker:
        - image: circleci/node:12-browsers
      steps:
        - checkout
        - restore_cache:
            name: Restore yarn package cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "jest-puppeteer-vuetify-test/yarn.lock"}}
              - yarn-packages-{{ checksum "yarn.lock" }}
              - yarn-packages-
        - run:
            name: Install test app
            working_directory: ./jest-puppeteer-vuetify-test
            command: yarn install --frozen-lockfile
        - run:
            name: Install dependencies
            command: yarn install --frozen-lockfile
        - save_cache:
            name: Save yarn package cache
            key: yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "jest-puppeteer-vuetify-test/yarn.lock"}}
            paths:
              - ~/.cache/yarn
        - run:
            name: Run test app
            working_directory: ./jest-puppeteer-vuetify-test
            command: yarn run serve
            background: true
        - run:
            name: Build project
            command: yarn run build
        - run:
            name: Run tests
            command: yarn run test
  workflows:
    version: 2
    ci:
      jobs:
        - lint
        - build
        - test
            requires:
              - build